### ISSUE TITLE
Pricing OK on product page, but shows lowest price in cart

### ISSUE THREAD

**Issue by vdwrcarlson** [organicinternet/magento-configurable-simple#48]
Hello,

I just installed version 0.8.2.MCMv2 on Magento 1.5.1.0, and it appears to be working fine initially, because on the product page, the "price from" is showing the lowest price, and when I change my options, the price updates correctly. However, when I add the item to the cart, it is still showing the base price (which is the price of the Configurable product) so I think it's actually adding the Configurable product to the cart, not the selected simple product.

I saw from other posts that it could be due to HTML changes on the product page, but we haven't made any. The form ID is right. However, I noticed (using Firebug) that the URL that the form is posted to ends in ,/product/365/ which is the ID of the Configurable product.

I saw another post here that said something about settings in the admin area ... however, when I click on "SCP Config" in the settings menu, Magento reports a file not found (404) error.

Note that I installed 0.8.2.MCMv2 manually, not through Magento Connect.

Any ideas?

**Comment by Bary** [comment]
404 error - it seems that you did not clear the cache. Do it and reindex your data.

**Comment by vdwrcarlson** [comment]
Thanks Bary ... I did refresh the cache and reindex all data prior to testing the extension. After reading your reply, I decided to try the two "flush" buttons on the top right of the cache management page, and that got the admin area working. However, the problem persists ... it appears to be adding the configurable product to the cart.

**Comment by Bary** [comment]
So 1 part is solved. So the second one ;)
It seems it did not installed correctly I guess. So here on github go to "Source" and Use button Download on the right part of Source page. After unzipping look at releasedVersions directory and choose OrganicInternet_SimpleConfigurableProducts-0.8.2.MCMv2.tgz. Use your Magento connect - there is no reason to install it manually. This step-by-step I followed and all is working as expected, into the cart is simple product inserted. Manually installation process is not clear for me I do not have experience with that, sorry.

**Comment by vdwrcarlson** [comment]
The reason I used manual installation is because I read here that with Magento Connect on Magento 1.5.1 (which is the version I use) it does not download the latest version ... it instead downloads 0.7.

I think you're saying that there is a way to use Magento Connect to install a locally-downloaded file. I'll give that a try. Thank you for the suggestion.

**Comment by Bary** [comment]
Correct! Use your manually downloaded file in your magento connect.

**Comment by vdwrcarlson** [comment]
I installed the 0.8.2.MCMv2 tgz file by uploading it in Magento Connect, and it installed successfully with no errors, but there is no change to the symptoms. Everything works great on the product page, but the Configurable Product (with the Configurable Product's price) is still shown in the cart.

Thank you very much for your assistance so far ... do you have any other suggestions for what I could try?

**Comment by vdwrcarlson** [comment]
I think I determined at least part of the problem ... the configurable products I've been working with were imported using a popular import extension. I just tried manually creating a configurable product (using the same attribute set) and it is working properly with that configurable product. So I think the issue must have something to do with how my products were imported. I'll do some more digging to see if I can figure it out. Please let me know if you have any idea why the imported products wouldn't be working with this extension, when manually created configurable products work fine. If you have any idea, it might help me know what to look for. :) Thanks!!

**Comment by cschuler-2024** [comment]
I have opposite problem.  The product page always shows the lowest price, no matter which attributes are selected. But when the item is added to cart, it correctly shows the higher price of the simple item.

The products were set up manually (I'm not using the cart for live production yet).

magento 1.6,  SCP 7.4
I also tried upgrading to SCP 8.2. Same issue.

**Comment by wwrivers** [comment]
I am having the same problem as cshuler.  Price doesn't change on the product page, but when product is added to cart it is correct. I am on magento 1.5.1.0 and SCP 7.4.  I will try to upgrade to 8.2. Anyone have any solutions?

Thanks!

**Comment by cschuler-2024** [comment]
I think I "fixed" this by setting the configurable item to an artificially high price.  Then, it would pull in the lowest simple item price.

**Comment by wwrivers** [comment]
Thanks for the reply. I have a high price set for the configurable product, but only the lowest price is ever displayed, even when no configurable options have been selected. At that point it says "Price From" and then shows the lowest priced configurable option. No matter what option is selected, it then changes the price to the lowest price, even if that is not the price of the product selected. 

Any suggestions?

**Comment by rwanninkhof** [comment]
I can confirm this issue... I always thought it had something to do with the multi site/store configuration. @wwrivers can you confirm this is happening on the non-default website?

**Comment by cschuler-2024** [comment]
wwrivers:

Are you talking about the price that appears on the product page in this section?

``` HTML
<div class="product-options-bottom">
  <div class="price-box">
  <span class="label" id="configurable-price-from-1_clone">
     <span class="configurable-price-from-label">Price From:</span>
  </span>
  <span class="regular-price" id="product-price-1_clone">
     <span class="price">$0.0991</span>
  </span>
  </div>
</div>
```

Then, yes, that isn't updating.  And I don't see any place in the code that even tries to update it (but i might be missing it).

rwanninkhof:

Yes, this is on the non-default website.

**Comment by wwrivers** [comment]
I don't have a multi store configuration -- just the default store /website.  

Yes, that is the area I am talking about (I don't know how to make my code show up here):

<div class="product-options-bottom">
<div class="price-box">
<span id="configurable-price-from-1_clone" class="label">
<span class="configurable-price-from-label"></span>
</span>
<span id="product-price-1_clone" class="regular-price">
<span class="price">$3,350.00</span>
</span>

What is funny is that I have used SCP on a different version of this site and it updated the price in that area.  That is why I am confused by what is happening now.

**Comment by cschuler-2024** [comment]
I think SCP is expecting the "reload" function (in product.js) to take care of that, but the code in that function is looking for an element named "product-price-1", not "product-price-1_clone". 

I got the price to update by adding a single line of code to  (your_path)/magento/js/varien/product.js ...

``` JAVASCRIPT
//AFTER THIS....

initPrices: function() {
this.containers[0] = 'product-price-' + this.productId;
this.containers[1] = 'bundle-price-' + this.productId;
this.containers[2] = 'price-including-tax-' + this.productId;
this.containers[3] = 'price-excluding-tax-' + this.productId;
this.containers[4] = 'old-price-' + this.productId; 

//ADD THE NEXT LINE...
this.containers[5] = 'product-price-' + this.productId + '_clone';
```

This should work for you.  But I still have other issues to resolve since I am using the ddq (drop-down quantity) mod (And I'd like the price to update after selecting a Qty as well), and since i'd like to show unit prices with 4 decimal places instead of 2. 

But that's my problem, not yours :)

**Comment by wwrivers** [comment]
Cschuler, that is awesome! That seems to do the trick!  Thanks!!!!!!!

**Comment by rwanninkhof** [comment]
cschuler You're the man!!! Thanks! :)

**Comment by cschuler-2024** [comment]
I should give the caveat that I am not yet using Magento in a production environment, so this hasn't been fully tested, and I'm not entirely sure if this wont have any unintended consequences elsewhere on the site.  I've only been playing with Magento for a few weeks, and I'm not that knowledgeable about the code being modified.  The above fix was the result of 30 minutes worth of troubleshooting using Firebug and few grep queries, so.... use at your own risk, etc, etc, etc...

Let me know if you find any problems.

---

And BTW ... to post code on this site you do this...

``` LUA
'''JAVASCRIPT
      var optionsPrice = something;
      var anothervar = somethingelse;
'''
```

Note that the three ` characters you need to use are are the "backward apostrophe", not the regular apostrophe that I used in the example above. (Im not sure how to escape the actual characters for my example)  On my keyboard, the backwards apostrophe is in the upper left hand corner, on the same key as the tilde (~)

On the first line after the three ` characters, you can specify the language you'd like the code to be parsed as (ie "JAVASCRIPT", "PHP", "HTML", or "BASH" ). You can find a complete list of supported languages here ... http://pygments.org/languages/

**Comment by dcolumbus** [comment]
I've flushed cache 100 times in every way, indexed the data another 100 ... 404 error.

**Comment by cschuler-2024** [comment]
Another change to the same file ( /var/www/html/magento/js/varien/product.js )

Around line 480:

``` PHP
       if($('product-price-'+this.config.productId)){
            $('product-price-'+this.config.productId).innerHTML = price;
         //Add next line to make system update price on screen. Perhaps should just replace previous line?
            $('product-price-'+this.config.productId+"_clone").innerHTML = price;
        }
        this.reloadOldPrice();
```

Magento 1.6.1
